CREATE TABLE IF NOT EXISTS task_defaults (
  id TEXT PRIMARY KEY DEFAULT 'default',
  channel_join_title TEXT DEFAULT 'Join Telegram Channel',
  channel_join_instructions TEXT DEFAULT 'Join the Telegram channel to complete this task.',
  channel_join_logo TEXT DEFAULT '',
  channel_join_category_icon TEXT DEFAULT '',
  bot_start_title TEXT DEFAULT 'Start Telegram Bot',
  bot_start_instructions TEXT DEFAULT 'Open and start the Telegram Bot or Mini App to complete this task.',
  bot_start_logo TEXT DEFAULT '',
  bot_start_category_icon TEXT DEFAULT '',
  x_follow_title TEXT DEFAULT 'Follow on X',
  x_follow_instructions E'Follow the X account to complete this task.\n\nSubmit a screenshot as proof below.',
  x_follow_logo TEXT DEFAULT '',
  x_like_title TEXT DEFAULT 'Like X Post',
  x_like_instructions E'Open the post and leave a like.\n\nSubmit a screenshot as proof below.',
  x_like_logo TEXT DEFAULT '',
  x_retweet_title TEXT DEFAULT 'Repost X Post',
  x_retweet_instructions E'Repost the post from your X account.\n\nSubmit a screenshot as proof below.',
  x_retweet_logo TEXT DEFAULT '',
  x_comment_title TEXT DEFAULT 'Comment on X Post',
  x_comment_instructions E'Leave a comment on the post as requested.\n\nSubmit a screenshot as proof below.',
  x_comment_logo TEXT DEFAULT '',
  ig_follow_title TEXT DEFAULT 'Follow on Instagram',
  ig_follow_instructions E'Follow the Instagram account to complete this task.\n\nSubmit a screenshot as proof below.',
  ig_follow_logo TEXT DEFAULT '',
  ig_like_title TEXT DEFAULT 'Like Instagram Reel',
  ig_like_instructions E'Open the reel and leave a like.\n\nSubmit a screenshot as proof below.',
  ig_like_logo TEXT DEFAULT '',
  ig_comment_title TEXT DEFAULT 'Comment on Instagram Reel',
  ig_comment_instructions E'Leave a comment on the reel as requested.\n\nSubmit a screenshot as proof below.',
  ig_comment_logo TEXT DEFAULT '',
  ig_repost_title TEXT DEFAULT 'Repost Instagram Reel',
  ig_repost_instructions E'Share or repost the reel to complete this task.\n\nSubmit a screenshot as proof below.',
  ig_repost_logo TEXT DEFAULT '',
  dc_join_title TEXT DEFAULT 'Join Discord Server',
  dc_join_instructions E'Join the Discord server to complete this task.\n\nSubmit a screenshot as proof below.',
  dc_join_logo TEXT DEFAULT '',
  custom_title TEXT DEFAULT 'Custom Task',
  custom_instructions TEXT DEFAULT 'Complete the custom task as described.',
  custom_logo TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO task_defaults (id) VALUES ('default') ON CONFLICT (id) DO NOTHING;
